### ISSUE TITLE
Rename repositories for the sake of readability and clarity

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#1]
Each language track should be named after the slug of the programming language—no 'x' prefix. The x-common repository should be named `problem-specifications`.

First test with one of the inactive tracks to see how Trackler handles it, and what happens with the x-api and the website. It needs to have at least one exercise.

**UPDATE: Since renaming the track adds a redirect, the change is seamless.**

See the discussion in https://github.com/exercism/discussions/issues/103

**TODO**

- [x] Make sure that each team is named after the track ID
- [x] Rename tracks (scripted)
- [x] Script a PR to update the config's repository URL
- [ ] Search through docs and code and fix references to `http://github.com/exercism/x*`

**Comment by kytrinyx** [comment]
@exercism/golang I'm going to rename the team to @exercism/go to match the track ID.

Update: we also have @exercism/perl which doesn't directly map to the track IDs of perl5 and perl6, and we have a number of @exercism/lisp tracks that don't have their own teams. I've suggested that we add teams for each track, and nest them under a parent team.

**Comment by petertseng** [comment]
and while we're at it don't forget that the https://github.com/orgs/exercism/teams/io team is confusingly not about the Io language, which will cause confusion when the Io language gets a track.

You can probably assume I'm joking and don't need to do anything with that team.

**Comment by kytrinyx** [comment]
> You can probably assume I'm joking and don't need to do anything with that team.

I could probably assume that, but I'm going to be cleaning up team names, and will clean that one up too :)

**Comment by kytrinyx** [comment]
@exercism/xruby @exercism/ruby what's the difference between these two teams? Do they have different purposes? If so, can we rename them to clarify that (and also nest one under the other)?

**Comment by kytrinyx** [comment]
I did some digging and it turns out @exercism/xruby's members are a subset of @exercism/ruby's members. I'm going to delete the xruby team, as it doesn't seem to serve a direct purpose.

If you do see a separate purpose, let's talk about it in the discussions repository, and maybe we can make something consistent for all the tracks.

**Comment by Insti** [comment]
I've no idea why there is 2 ruby groups. Deleting xruby seems fine.

**Comment by kytrinyx** [comment]
I've run a script to make sure that all the track repositories have a team with push permissions that is named after the track ID. Where there are discrepancies I've `@`-mentioned the maintainers of the tracks in question to discuss.

**Comment by kotp** [comment]
Thanks @kytrinyx

**Comment by kytrinyx** [comment]
I've tested this with the VB.NET track, and the change was completely seamless.

**Comment by arcuru** [comment]
@kytrinyx FYI, it looks like renaming the repos breaks any stored urls to travis-ci. I think this only really affects the 'status' button that's in most (or all?) of the track README's.

**Comment by kytrinyx** [comment]
Ah, yepp--I will write a script to update that! Thanks for catching it @patricksjackson

**Comment by petertseng** [comment]
This is FYI only and no actions are necessary in response.

Respository names of the form e.g. `exercism/haskell` seem to make sense and be unambiguous given that someone knows what Exercism is. I was worried, however, that forking it to my own username as `username/haskell` might give the impression that I'm working on the entire language, or something of that sort. So I am forking to `username/exercism-haskell` instead.

/shrug

**Comment by kotp** [comment]
@petertseng this is also the reason I have not renamed the forks I have to plain language names, preferring the `x` prefix.

**Comment by kytrinyx** [comment]
> I was worried, however, that forking it to my own username as username/haskell might give the impression that I'm working on the entire language, or something of that sort.

This didn't occur to me until I had already made the change. Under `exercism/haskell` it makes sense, when forked, less so.

> So I am forking to username/exercism-haskell instead.

Is there a way to do that directly in the user interface?

/cc @exercism/julia

**Comment by petertseng** [comment]
> >  So I am forking to username/exercism-haskell instead.

> Is there a way to do that directly in the user interface?

Hmm, I appear not to have found one. I have to fork with the unqualified name and then rename it afterward.

**Comment by kotp** [comment]
This is a point that could be suggested in the reading.  (Otherwise searching for language repositories in github could very well be a "pollution" caused by the Exercism project forks.)  I don't think we want to be the cause of that for new folks, it is confusing enough as it is starting out.

**Comment by yurrriq** [comment]
We could include a shell snippet for forking to a different name. I know introducing more tooling is probably not ideal, but [`hub`](https://github.com/github/hub) is good at this sort of thing.

**Comment by tleen** [comment]
Unless you are actually working on the language on GitHub is the issue here that it may be misleading?

**Comment by NobbZ** [comment]
As I am reading all these true and valid concerns... What will happen when user U (a contributor to language L) has already forked that languages repo under U/L does now fork exercism/L?

**Comment by tleen** [comment]
That seems to be the the issue: if you are working on the core language there is a naming conflict with the fork **and** its unresolvable via the GitHub UI as part of the working process: "You already have a fork of this repository:". 

This may be a legit GitHub issue? That you can't fork two **distinct** repositories with the same name.

**Comment by SaschaMann** [comment]
> What will happen when user U (a contributor to language L) has already forked that languages repo under U/L does now fork exercism/L?

The fork of exercism/L will be called U/L-1. Afterwards it can be renamed (https://github.com/exercism/julia/pull/68#issuecomment-309756496).

---

Renaming the repos to L-track might be nicer, it doesn't have the issues that just L has but it's not as arbitrary as xL.

**Comment by tleen** [comment]
GitHub lets you do it. So it's not on them. Make make sense to use a snippet then.

**Comment by kytrinyx** [comment]
I think that there are a couple of good options here:

* rename to `$TRACK_ID-track`

or

* document how this works and what to do, and
* provide a `hub` snippet that will do it automatically (great if you already use hub, but probably not worth installing hub for)

**Comment by catb0t** [comment]
Will https://github.com/exercism/problem-specifications exist soon? It was mentioned in the original comment but it doesn't seem like anyone followed up on that.

**Comment by kytrinyx** [comment]
Oh! @catb0t I forgot about that one. I'll do it right now.

**Comment by kytrinyx** [comment]
Alright. We're done here. There are still a couple of PRs to be merged, but they're in repositories that are maintained.

Thanks y'all!
