### ISSUE TITLE
Remove support for exercises in the root dir

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#3]
All the tracks now have moved their exercises into the `exercises/` subdirectory.

**TODO**

- [x] Update Trackler - done https://github.com/exercism/trackler/pull/44
- [x] Update Configlet to only check the `exercises` subdirectory and not worry about ignored directories
  - https://github.com/exercism/configlet/pull/17
- [x] Release new configlet
- [x] Update https://github.com/exercism/request-new-language-track to remove "ignored" from config.json
  - https://github.com/exercism/request-new-language-track/pull/30
- [x] Write script and update all the tracks to remove "ignored" from config.json
  - https://github.com/exercism/meta/pull/7
- [x] Update `config.json` documentation
  - https://github.com/exercism/docs/issues/12
  - https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#track-configuration-file
  - https://github.com/exercism/request-new-language-track/blob/master/CHECKLIST.md
  - https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md

**Comment by Insti** [comment]
[todo list moved to original issue for tracking -kytrinyx]

**Comment by kytrinyx** [comment]
I've added a PR to configlet to stop supporting exercises in the root dir.

**Comment by kytrinyx** [comment]
The new configlet is released. I ran the script against the Chapel track (https://github.com/exercism/xchapel/pull/7), and it passes the build.
