### ISSUE TITLE
Submit PRs to fix all deprecated file locations in tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#94]
See discussion in https://github.com/exercism/configlet/issues/94

- [x] Rename: `$TRACK_ROOT/exercises/$SLUG/HINTS.md` -> `$TRACK_ROOT/exercises/$SLUG/.meta/hints.md`
- [x] Delete the `docs/EXERCISE_README_INSERT.md` if it's empty
- [x] Lock bob description if implementation hasn't added new rule
- [x] Update Java track to remove unnecessary overridden template
- [x]  Inline `$TRACK_ROOT/docs/EXERCISE_README_INSERT.md` and `$TRACK_ROOT/config/exercise-readme-insert.md`, 

-------

Note to self: ongoing work in `bin/inline-inserts`. Canary PRs are submitted.
Also waiting for Java's template override deletion PR to be merged.
